### ISSUE TITLE
Qt 5.6.2 vc14_4 (py3) post-link script breaks Python when Miniconda in the root uses Python 2

### ISSUE THREAD

**Issue by tadeu** [ContinuumIO/anaconda-recipes#106]
This line was added to the Qt post-link script:

```
CHCP 65001
```

This is known to break Python 2 (and subsequently `conda`), giving the error:

```
LookupError: unknown encoding: cp65001
```

And because the script is executed by the `python` in the root env, it doesn't matter that the env where Qt is installed is a Python 3 env.

(there is a workaround for this, which is setting the environment variable `PYTHONIOENCODING=utf-8`)

**Comment by mingwandroid** [comment]
Thanks for the report. I am testing a fix now.

**Comment by mingwandroid** [comment]
This should be fixed now, please test via: `conda update qt`
