### ISSUE TITLE
Missing Numba 0.34 packages for win64.

### ISSUE THREAD

**Issue by Maxyme** [ContinuumIO/anaconda-recipes#120]
Numba has recently been updated to 0.34, however the following Numba packages for windows are missing on the anaconda channel:

1. win-64/numba-0.34.0-np113py36_0.tar.bz2 and
2. win-64/numba-0.34.0-np112py36_0.tar.bz2

**Comment by mingwandroid** [comment]
The win-32 ones were also missing. I have fixed this now.
