### ISSUE TITLE
Scikit-Image 0.13.* has too strict requirements for networkx on OSX

### ISSUE THREAD

**Issue by patricksnape** [ContinuumIO/anaconda-recipes#135]
@msarahan Any idea who pushed the OSX builds for scikit-image?

scikit-image 1.13.1 specifies the following package dependencies on OSX:

```
scikit-image 0.13.1 py36hd1453f6_0
----------------------------------
file name   : scikit-image-0.13.1-py36hd1453f6_0.tar.bz2
name        : scikit-image
version     : 0.13.1
build string: py36hd1453f6_0
build number: 0
channel     : defaults
size        : 22.5 MB
arch        : None
license     : BSD 3-Clause
license_family: BSD
md5         : f7459e360945c24573a276d31e9deb93
noarch      : None
platform    : None
subdir      : osx-64
timestamp   : 1511319218570
url         : https://repo.continuum.io/pkgs/main/osx-64/scikit-image-0.13.1-py36hd1453f6_0.tar.bz2
dependencies:
    dask >=0.5
    imageio >=2.1.0
    matplotlib >=1.3.1
    networkx >=1.8,<2.0
    numpy >=1.9.3,<2.0a0
    pillow >=2.1.0
    python >=3.6,<3.7.0a0
    pywavelets >=0.4.0
    scipy >=0.17
    six >=1.7.3
```

where `networkx` is specified as `>=1.8,<2.0` which is contrary to the [`requirements.txt`](https://github.com/scikit-image/scikit-image/blob/v0.13.1/requirements.txt) file for scikit-image 0.13.1.

Would it be possible to push a new build number with this unncessary restriction removed? It's worth pointing out that this restriction doesn't seem to exist on linux64 and that there is a package for networkx 2 for OSX in defaults.

Also, conda-forge [does not have this strict requirement](https://github.com/conda-forge/scikit-image-feedstock/blob/master/recipe/meta.yaml)

**Comment by msarahan** [comment]
This repo is deprecated.  Everything is now at the https://github.com/AnacondaRecipes organization, which mimics conda-forge (mostly).  To check on who and why on this, and to ask for a fix, please file an issue on the feedstock (fork) at https://github.com/anacondarecipes/scikit-image-feedstock

**Comment by patricksnape** [comment]
Thanks @msarahan sorry!

**Comment by msarahan** [comment]
No worries at all.  Thanks for asking.
