### ISSUE TITLE
cudatoolkit 9.1 and 9.2?

### ISSUE THREAD

**Issue by jchodera** [ContinuumIO/anaconda-recipes#140]
The `cudatoolkit` packages in https://anaconda.org/anaconda/cudatoolkit/files seem to be missing the recent [CUDA 9.1](https://developer.nvidia.com/cuda-91-download-archive) and [CUDA 9.2](https://developer.nvidia.com/cuda-downloads) releases. Is there an ETA for these?

**Comment by jakirkham** [comment]
@jjhelmus, is there anything we can do to help? :)

**Comment by jjhelmus** [comment]
Sorry for the delayed response, I've been on vacation last week and am at the SciPy conference this week.  I will look at getting out `cudatoolkit` 9.1 and 9.2 when I am back in the office.  Typically we like to release packages (PyTorch, CuPy, Caffe, etc) which make use of the new version at the same time as `cudatoolkit`.  The recipe we use for `cudatoolkit` is in the [numba/conda-recipe-cudatoolkit repository](https://github.com/numba/conda-recipe-cudatoolkit).  That recipe has CUDA 9.1 but is missing 9.2.  A PR to add 9.2 support would help move this forward.

**Comment by jakirkham** [comment]
cc @scopatz @xmnlab

**Comment by jakirkham** [comment]
No worries. Thanks for the update and info. That is very helpful.

There was some work on this front in conda-forge, which may be useful. ( https://github.com/conda-forge/staged-recipes/pull/6240 )

**Comment by xmnlab** [comment]
hi everyone! 
thanks @jakirkham to cc us here!

we saw the approach used by numba but we decided to use a simple approach just using shell scripts 
and we are using the test method from numba.

now I am working to finish osx and win scripts.

basically we now are waiting for some resolution on https://github.com/conda-forge/conda-forge.github.io/issues/63

**Comment by jjhelmus** [comment]
cudatoolkit 9.2 is now available in `defaults` for the linux-64 platform.

**Comment by jayfurmanek** [comment]
Very cool!
Which recipe did you guys use? I don't see the numba recipe updated at https://github.com/numba/conda-recipe-cudatoolkit

edit:
I see your PR:
https://github.com/numba/conda-recipe-cudatoolkit/pull/11

**Comment by jjhelmus** [comment]
The necessary changes to the numba recipe are in numba/conda-recipe-cudatoolkit#11

**Comment by jakirkham** [comment]
This can be closed, right?

**Comment by jjhelmus** [comment]
Yes, this can be closed.  cudatoolkit  9.1 and 9.2 are available in `defaults`

**Comment by tashrifbillah** [comment]
Hi @jjhelmus , only 9 and 9.2 are available but I do not see 9.1:
https://anaconda.org/anaconda/cudatoolkit/files

Can you check it?
