### ISSUE TITLE
keras recipe pulls the wrong version of tensorflow

### ISSUE THREAD

**Issue by jlopezpena** [ContinuumIO/anaconda-recipes#142]
There are two separate versions of keras, `keras` and `keras-gpu`. The plain version (meant to use cpu) is pulling `tensorflow` as a dependency, but as of tensorflow 1.12 this defaults to 
`tensorflow                    1.12.0 gpu_py36he68c306_0  pkgs/main` (or similar)
this causes errors about missing PyCuda libraries.

Plain keras should pull the `eigen` or `mkl` versions instead of the `gpu` one, unless `keras-gpu` is specified.

**Comment by jjhelmus** [comment]
Can you provide details on the platform and conda version where you are seeing this behavior?  The output of `conda info` should be sufficient.

**Comment by jlopezpena** [comment]
I managed to track down the problem; cause seems to be an staged build of docker containers, one of which contained an old version of tensorflow (1.8) that somehow managed to "upgrade" itself to the wrong variant in a further stage.

Upon a clean install everything builds and install as expected, so I am closing the issue.

Sorry for the noise!
