### ISSUE TITLE
Add missing components to `ipython-notebook` 4.x package

### ISSUE THREAD

**Issue by jakirkham** [ContinuumIO/anaconda-recipes#17]
The following were components in the original iPython 3.x along with their post split counterparts.<sup>1</sup>

* [x] IPython.utils.traitlets ⇒ traitlets
* [x] IPython.config ⇒ traitlets.config
* [x] IPython.html ⇒ notebook
* [x] IPython.nbconvert ⇒ nbconvert
* [x] IPython.nbformat -> nbformat
* [ ] IPython.parallel ⇒ ipyparallel
* [ ] IPython.qt ⇒ qtconsole
* [ ] IPython.terminal.console ⇒ jupyter_console
* [x] Python.kernel ⇒ jupyter_client, ipykernel
* [x] IPython.kernel.zmq.session ⇒ jupyter_client.session
* [x] IPython.kernel.zmq.kernelapp ⇒ ipykernel.kernelapp
* [x] miscellaneous ⇒ ipython_genutils
* [ ] IPython.html.widgets ⇒ ipywidgets \*

Checked component appear in the `ipython-notebook` 4.x package. Unchecked ones are missing when installing `ipython-notebook`. It would be nice if the missing counterparts were included in the `ipython-notebook` package to make this transition a bit more seamless when making the transition.

[1] - http://blog.jupyter.org/2015/04/15/the-big-split/
\* - Occurred after the blog post was published. Also, will be split further.

**Comment by msarahan** [comment]
See also: https://github.com/ContinuumIO/anaconda-issues/issues/470

I disagree with the reasoning here.  While it makes things more convenient from an installation point of view and a backwards-compatibility point of view, in my opinion the split of the IPython project was a good thing.  Does it make sense that the notebook itself drags in qtconsole?  It is completely independent.  If you want to use both, have at it.  I just think you should have to explicitly install both (and as annoying as it is to break backwards compatibility, the IPython team made a good long-term decision).

If you want the old behavior, I think we should create a metapackage that installs the kitchen-sink version of IPython.  This should not be the default.

**Comment by jakirkham** [comment]
I would be ok with that alternative. If there was an `ipython-all` package for the interim that would be very useful.

Right or wrong, the reality is it can be kind of surprising to miss a part of a dependency. For my particular case, I was missing `ipyparallel`.

**Comment by msarahan** [comment]
yeah, I totally agree: breaking backwards compatibility is not a decision to be taken lightly.

I will put together an ipython-all metapackage.  Where would be the best place (in your opinion) to document this, so people know to look for it?

**Comment by jakirkham** [comment]
Thanks. I appreciate that. Let me think about it and get back to you.

**Comment by jakirkham** [comment]
I think that list is missing `ipywidgets`, as well. I don't know what your opinion would be about including them in base, but it would be nice if they were in `ipython-all`.

**Comment by ilanschnell** [comment]
Most of these should be available now.
