### ISSUE TITLE
Update ipyparallel to 4.1.0

### ISSUE THREAD

**Issue by jakirkham** [ContinuumIO/anaconda-recipes#18]

**Comment by jakirkham** [comment]
Thoughts on this? Should be relatively straightforward. It also includes pymongo 3 support.

**Comment by ccordoba12** [comment]
Closing as there's now a PR in conda-recipes.

**Comment by jakirkham** [comment]
Could we please get a built package in the `defaults` channel?

**Comment by jakirkham** [comment]
@ccordoba12, sorry to pester, but could we please see this in `defaults`? This includes a fix for `pymongo` 3.x amongst other things.

**Comment by ccordoba12** [comment]
Don't worry, and sorry for the big delay in updating this package. I'll send a pull request to our internal repo today.

Hopefully new packages will be available in a couple of days :-)

**Comment by jakirkham** [comment]
Ok, sorry for complaining. Thanks, @ccordoba12.

**Comment by jakirkham** [comment]
Just saw the new packages, thanks again @ccordoba12.

**Comment by ccordoba12** [comment]
You're welcome!
