### ISSUE TITLE
Readline package appears broken (Linux)

### ISSUE THREAD

**Issue by jakirkham** [ContinuumIO/anaconda-recipes#19]
It appears the copy of `readline` that now fills the channels, possibly the same one provided here, is broken. To see what I mean, try downloading any of the docker images and install `ipython` with `conda`. The colors are missing, tab completion fails, using up/down arrows to traverse history fails. This is normally due to a broken `readline` or a copy of python that failed to link against `readline`. This really hurts the usability of things like the terminal based iPython.

**Comment by msarahan** [comment]
Just for scope, what platform(s) have you found this on? I think it is
working on Windows at least, but will investigate Linux and Mac.

**Comment by jakirkham** [comment]
Certainly, Linux. It happened on Python 2.7 and 3.4. May be happening on other Python's, as well.

I tried creating a simple environment on Mac with `ipython`, but it appears this issue didn't appear. In short, just Linux.

**Comment by jakirkham** [comment]
I think this may even only be an issue with the docker images. Not sure why though. Does this link to any other system libraries?

**Comment by jakirkham** [comment]
Closing in favor of https://github.com/ContinuumIO/docker-images/issues/19
