### ISSUE TITLE
Anaconda builds python-2.7.11-5 and later drop bin/python2.7 as not linked, resulting in incorrect sys.prefix

### ISSUE THREAD

**Issue by itldo** [ContinuumIO/anaconda-recipes#28]
The current python recipe specifies a

build:
 nolink:
    bin/python

which should probably refer to bin/python2.7 instead.
bin/python is itself a symbolic link to python2.7.

Because python2.7 is linked to the package directory on install

python -> python2.7
python2 -> python2.7
python2.7 -> /home/username/.conda/envs/.pkgs/python-2.7.11-5/bin/python2.7

python itself thinks it is running out of the package directory
and sets sys.prefix accordingly.

If python2.7 is installed as a copy,
then python sets sys.prefix to the conda environment path.

It should look like this:

python -> python2.7
python2 -> python2.7
python2.7 (a copy)

Versions 2.7.11 build 0 and before contain bin/python2.7 in the file that excludes links.

python-2.7.11-0/info$ cat no_softlink
bin/python
bin/python-config
bin/python2
bin/python2.7

-tim

**Comment by ilanschnell** [comment]
Thanks.  `python2.7` is the only file which shouldn't be soft-linked.  I'll fix that.

**Comment by ilanschnell** [comment]
It is fixed in `python-2.7.12-1` (the latest Unix Python 2.7).
See also: https://github.com/ContinuumIO/anaconda-issues/issues/870
