### ISSUE TITLE
Shapely depends on numpy ABI

### ISSUE THREAD

**Issue by pelson** [ContinuumIO/anaconda-recipes#36]
Shapely uses Cython to speed up some operations, and therefore depends on the numpy ABI. Please see https://github.com/conda-forge/shapely-feedstock for a (longstanding) recipe that correctly builds Shapely.

**Comment by rsignell-usgs** [comment]
@ilanschnell, any word on this?

**Comment by pelson** [comment]
Pretty sure this is now obsolete.
