### ISSUE TITLE
xz recipe does not copy all relevant license files

### ISSUE THREAD

**Issue by tylere** [ContinuumIO/anaconda-recipes#41]
The xz package's license is spread across multiple files:
COPYING
COPYING.GPLv2
COPYING.GPLv3
COPYING.LGPLv2.1

However, the conda recipe [meta.yaml file refers to only one of the license files](https://github.com/ContinuumIO/anaconda-recipes/blob/master/xz/meta.yaml#L19): COPYING

As a result, the conda package does not include a copy of the license, which is required by the GPL license(s).

**Comment by ilanschnell** [comment]
Thanks, for reporting.  All license files are included in the `xz` packages now (and available on the default repository).
