### ISSUE TITLE
libevent missing Python dependency

### ISSUE THREAD

**Issue by jakirkham** [ContinuumIO/anaconda-recipes#44]
Appears the `libevent` recipe is not open sourced AFAICT or at least it is not in this repo. In any event, I'm going to put this issue here as I can't think of a more appropriate place to put it ATM. Should add `libevent` does [appear](https://anaconda.org/anaconda/libevent) in the `anaconda` channel. So this seems reasonable.

After recently working on a `libevent` recipe in PR ( https://github.com/conda-forge/staged-recipes/pull/1491 ), it has become clear to me that `libevent` depends on Python. This is because it installs a script to the `bin` directory called `event_rpcgen.py`. Not only does it depend on Python, but that script appears to [hard-code Python 2](https://github.com/libevent/libevent/blob/release-2.0.21-stable/event_rpcgen.py#L1). Thus `libevent` should depend on Python 2.x for run and build.

**Comment by jakirkham** [comment]
Any thoughts on this?

**Comment by jakirkham** [comment]
Friendly nudge. Would love to understand what plans there are to fix this issue.

**Comment by ilanschnell** [comment]
I would not consider `libevent` a Python package, just because it contains a Python script, because it does not install a Python library (into site-packages) which you can import.  The plan is to remove the script `event_rpcgen.py` (in order to avoid confusion) and not add Python as a dependency.

**Comment by jakirkham** [comment]
That sounds completely reasonable. Will follow suit then. Thanks.
