### ISSUE TITLE
Add pyside recipe

### ISSUE THREAD

**Issue by synapticarbors** [ContinuumIO/anaconda-recipes#45]
pyside is available through the default channel, but it's recipe is not in this repo. It would be great to add this at some point.

**Comment by jakirkham** [comment]
Maybe they are using the [one]( https://github.com/conda/conda-recipes/tree/a796713805ac8eceed191c0cb475b51f4d00718c/python/pyside ) from `conda-recipes`?

**Comment by almarklein** [comment]
I don't think that there ever was a PySide recipe that really worked.

**Comment by almarklein** [comment]
Oh right, but the package is in the main channel. I thought that CA was going forward with PyQt and leaving PySide for what it was...

**Comment by mingwandroid** [comment]
PySide is now an official Qt project and is limberness under the same terms as the rest of Qt. For those reasons I think providing PySide is a good idea.

**Comment by ccordoba12** [comment]
A recipe is being worked out in conda-forge/staged-recipes now.

**Comment by jakirkham** [comment]
xref: https://github.com/conda-forge/staged-recipes/pull/1684

**Comment by ilanschnell** [comment]
Anaconda used to support PySide years ago, but not anymore (after switching to PyQt).
