### ISSUE TITLE
ipywidgets repo name conflict

### ISSUE THREAD

**Issue by jasongrout** [ContinuumIO/anaconda-recipes#5]
We recently decided to name the IPython widget repo `ipywidgets` (see https://github.com/ipython/ipywidgets), and we have the ipywidgets name on pypi (https://pypi.python.org/pypi/ipywidgets/).  Unfortunately, this conflicts with this repo's ipywidgets package from Jake Vanderplas.

**Comment by groutr** [comment]
We can rename the current package to ipywidgets-static or something.

**Comment by damianavila** [comment]
We can probably ask @jakevdp about the name since AFAIK his `ipywidgets` is not supported anymore...

**Comment by jakevdp** [comment]
I'd be happy to rename my repo

**Comment by groutr** [comment]
Apparently, there are still people who are using it, since the package was created as a response to a request we received.

I renamed the recipe to static_ipywidgets.  @jakevdp, I don't think a rename is necessary for this package.
