### ISSUE TITLE
Question regarding conda-lua-science

### ISSUE THREAD

**Issue by kirk86** [ContinuumIO/anaconda-recipes#51]
Hello, everyone I've been trying to install `conda-lua-science` packages on a centos 6.6. It installs fine without any problems but when I test it I always get an error.  I don't know if this is the right place to ask this question, let me know?

The error that I'm getting is the following one.

```
/home/user/anaconda2/share/lua/5.1/trepl/init.lua:384: loop or previous error loading module 'torch'
stack traceback:
	[C]: in function 'error'
	/home/user/anaconda2/share/lua/5.1/trepl/init.lua:384: in function 'require'
	[string "_RESULT={require('torch')}"]:1: in main chunk
	[C]: in function 'xpcall'
	/home/user/anaconda2/share/lua/5.1/trepl/init.lua:652: in function 'repl'
	...e/user/anaconda2/lib/luarocks/rocks/trepl/scm-1/bin/th:199: in main chunk
	[C]: at 0x00405100
```

Thanks!

**Comment by msarahan** [comment]
Those are not packages that Continuum provides.  You need to ask whomever you've obtained those packages from.

**Comment by kirk86** [comment]
@msarahan Thanks!
