### ISSUE TITLE
Qt 5.6.0 package totally broken

### ISSUE THREAD

**Issue by Ypnose** [ContinuumIO/anaconda-recipes#52]
Hi,
After updating an existing Anaconda distribution that was installed your with shiny 400M installer, Qt was bumped to ```5.6.0```:

```
$ ./conda list qt
# packages in environment at /opt/anaconda-testing:
#
pyqt                      5.6.0                    py35_0  
qt                        5.6.0                         0
```
But there is a problem: when this environment is installed in ```/opt```, some permissions are just brainless. Indeed, after this update, ```anaconda3/bin/qt.conf``` (it is just a directory example) is set to ```750``` permissions:
```
$ stat qt.conf
  File: 'qt.conf'
  Size: 157             Blocks: 8          IO Block: 4096   regular file
Device: 801h/2049d      Inode: 2816378     Links: 1
Access: (0750/-rwxr-x---)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2016-10-06 15:09:38.961687000 +0200
Modify: 2016-10-06 15:10:22.752769805 +0200
Change: 2016-10-06 15:10:22.752769805 +0200
 Birth: -
```
With Qt ```4.8.7```, it was ```664``` which is much smarter.

**Consequences**:
You just broke 50 machines in my infrastructure and my scientists are now unable to use other Python tools (like ```pyzo```). In fact, the Python shell fails to load modules (```xcb``` for example) because the paths are not defined. Yes, regular users cannot read that bloody file because they are in the ```other``` group! It took 1,5 day for me to debug it, thanks to ```strace(1)```.

**Fixes**
Maybe you should learn UNIX permissions / rights. This is extremely unprofessional for a company! This is why I will not recommend your twisted snake env. Another new reason why I hate this kind of "packager manager", where the maintainers are unable to correctly maintain packages. Or perhaps, I should not update packages to make sure everything works…

Oh BTW, rollbacking doesn't work because a symlink already exists. I had to remove it by hand. I will not open another issue because I'm pretty sure we will find another bunch of flaws.

**Comment by ccordoba12** [comment]
Please follow conda/conda-build#1435 for a possible fix. We don't know what happened in this case, sorry.

> This is why I will not recommend your twisted snake env

Closing, as it seems you don't want to keep using Anaconda in the future.

**Comment by mingwandroid** [comment]
AFAICT, you could've simply used chmod on qt.conf but that's not much fun I suppose?

**Comment by Ypnose** [comment]
It seems you didn't read the first report. I invite you to do so. The problem started yesterday and the real "fix" was found this afternoon. When I found what was the problem, yeah the fix was easy. Thankfully, I had strace to help me with broken packages.

In the meantime, there were cancelled teaching and researchers not being to work. I do not know if you understand the problematic… For a product designed as an "open data science platform", it is kinda awful. I won't tell you how rollbacking Qt is also prevented due an existing symlink.  
And don't get me wrong, I will still have to use this hacky manager even if it's probably one of the worst product I used in 10 years of UNIX (oh, and I'm not talking about your 400M binary script that was shared with no sums until recently).

**Comment by ccordoba12** [comment]
I don't know what kind of help(?) or support(?) you expect from us with this kind of trolling messages.

Too bad you have to use conda if you find it so unprofessional and unuseful, but that's your problem, not ours. So please don't take this open space to share your frustrations with us (it's not really helpful).

I'm locking this issue to avoid further abuse.
