### ISSUE TITLE
libxslt 1.1.29 introduces system dependencies which should be packaged (Linux)

### ISSUE THREAD

**Issue by gqmelo** [ContinuumIO/anaconda-recipes#66]
```libxslt``` was updated to ```1.1.29``` and it is now linking with additional system libraries which are not widely available across distributions:

```bash
$ conda create -n test libxslt
$ source activate test
(test) $ ldd $CONDA_PREFIX/lib/libexslt.so
	linux-vdso.so.1 =>  (0x00007ffde9957000)
	libxslt.so.1 => /home/guilherme/Work/miniconda/envs/test/lib/./libxslt.so.1 (0x00007f2ee49b8000)
	libxml2.so.2 => /home/guilherme/Work/miniconda/envs/test/lib/./libxml2.so.2 (0x00007f2ee465d000)
	libz.so.1 => /home/guilherme/Work/miniconda/envs/test/lib/./libz.so.1 (0x00007f2ee4447000)
	libiconv.so.2 => /home/guilherme/Work/miniconda/envs/test/lib/./libiconv.so.2 (0x00007f2ee4158000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f2ee3e1f000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f2ee3c15000)
	libgcrypt.so.11 => not found
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f2ee3a11000)
	libgpg-error.so.0 => /lib/x86_64-linux-gnu/libgpg-error.so.0 (0x00007f2ee37fd000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f2ee3436000)
	/lib64/ld-linux-x86-64.so.2 (0x000055ab7009d000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f2ee3218000)
```

I don't know about ```libgpg-error.so.0```, but ```libgcrypt.so.11``` should definitely not come from system as its API/ABI seems to constantly change (currently Ubuntu 16.10 ships ```libgcrypt.so.20```).

**Comment by ilanschnell** [comment]
Which `libxslt 1.1.29` package did you download.  I have see far fewer shared libraries being linked to:
```
$ ldd libxslt.so
	linux-vdso.so.1 =>  (0x00007fff549fd000)
	libxml2.so.2 => /opt/anaconda1anaconda2anaconda3/lib/././libxml2.so.2 (0x00002abf8acd1000)
	libz.so.1 => /opt/anaconda1anaconda2anaconda3/lib/././libz.so.1 (0x00002abf8b02d000)
	libiconv.so.2 => /opt/anaconda1anaconda2anaconda3/lib/././libiconv.so.2 (0x00002abf8b243000)
	libm.so.6 => /lib64/libm.so.6 (0x00002abf8b53e000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00002abf8b7c2000)
	librt.so.1 => /lib64/librt.so.1 (0x00002abf8b9c6000)
	libc.so.6 => /lib64/libc.so.6 (0x00002abf8bbcf000)
	/lib64/ld-linux-x86-64.so.2 (0x00000033fbe00000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00002abf8bf29000)
```
I downloaded `libxslt-1.1.29-0` from the default channel, and:
```
$ md5sum libxslt.so
02410a362d70b6aacd86d0ec836edf75  libxslt.so
```

**Comment by gqmelo** [comment]
@ilanschnell, thanks for replying
Please note that the problematic lib is lib**e**xslt.so, not libxslt.so

**Comment by ilanschnell** [comment]
I've reverted to `libxslt 1.1.28` for now, until a the `libexslt.so` problem is resolved.

**Comment by gqmelo** [comment]
@ilanschnell, unfortunately now the new ```1.1.28``` package (build number 3) is now linking with those libraries too.
So probably it is one of its dependencies that is bringing libgcrypt

**Comment by immerrr** [comment]
@ilanschnell could you please bump `lxml=3.7.2` to be able to run with `lxslt=1.1.28`?

Also, I can confirm that `1.1.28-0` works, whereas `1.1.28-3` does not.

**Comment by ilanschnell** [comment]
Hmm, the latest `lxml 3.7.2` is linked to `libxslt 1.1.29`, so I'm not sure why you are worried about `1.1.29` at this point.

**Comment by immerrr** [comment]
@ilanschnell I could have sworn I tried 1.1.29 and encountered the same error, before trying to downgrade to 1.1.28. Weirdly enough, after purging downloaded packages and redownloading both lxml & libxslt, it worked. Maybe it was a stale package that was downloaded before the fix.

Anyway, it seems to work now, thank you!

**Comment by ilanschnell** [comment]
I'm happy it works with `libxslt 1.1.29` for you now!
