### ISSUE TITLE
Update-request: line-profiler

### ISSUE THREAD

**Issue by MSeifert04** [ContinuumIO/anaconda-recipes#71]
I hope it's okay to simply ask here: Is it possible to update the `line_profiler` [package](https://github.com/ContinuumIO/anaconda-recipes/blob/08f84e7eb91ce1fbe4637a39b39d0a9a9b96f3fa/line_profiler/meta.yaml)? 

There has been a 2.0 release which fixed some ipython 5.x compatibility issues.

**Comment by MSeifert04** [comment]
Or is there any way I could help?

**Comment by ilanschnell** [comment]
It's not very hard to update this package, just a matter of doing it.  New packages will be available tomorrow.

**Comment by MSeifert04** [comment]
Thank you @ilanschnell 👍
