### ISSUE TITLE
Matplotlib Python 3.6 builds missing

### ISSUE THREAD

**Issue by astrofrog** [ContinuumIO/anaconda-recipes#76]
The Matplotlib builds for Python 3.6 appear to be missing from the defaults channel. Are there currently issues building this?

**Comment by mingwandroid** [comment]
Yes, the usual one, not enough time, too much to do :-)

We are working on it though.

**Comment by mingwandroid** [comment]
Which OS are you most concerned with?

**Comment by astrofrog** [comment]
@mingwandroid - MacOS X and Linux. Thanks!

**Comment by ilanschnell** [comment]
They're available, even matplotlib 2.0.0 now.
