### ISSUE TITLE
pillow 4.0.0 required by anaconda 4.3.0 misses a dependence to `olefile`

### ISSUE THREAD

**Issue by anjos** [ContinuumIO/anaconda-recipes#81]
Pillow 4.0.0 now requires a dependence on a Python package called `olefile` (just added to this recipe container). If you pip install something on a conda environment with anaconda 4.3.0 pre-installed that requires pillow, then it will try to download `olefile` from PyPI. Ideally, you should just depend on it.

ping @183amir

**Comment by anjos** [comment]
An implementation that seems right on conda-forge: https://github.com/conda-forge/pillow-feedstock/blob/master/recipe/meta.yaml

**Comment by 183amir** [comment]
I have also reported this issue here before: https://github.com/ContinuumIO/anaconda-issues/issues/1387 please update the `anaconda 4.3.0` package too if necessary to account for this.

**Comment by ilanschnell** [comment]
I've added the `olefile` dependency in `pillow-4.0.0` build 1.

**Comment by 183amir** [comment]
Thank you @ilanschnell I have tested the new version and it works.
