### ISSUE TITLE
conda-build-all 1.0.2

### ISSUE THREAD

**Issue by jakirkham** [ContinuumIO/anaconda-recipes#94]
Noticed that conda-build-all 1.0.1 was added to `defaults` and wanted to suggest that 1.0.2 be added as well. It fixed a bug with `conda-build` 2.x compatibility and some issues with R support. Would be nice if it were available given `conda-build-all` is already in defaults.

**Comment by ilanschnell** [comment]
I just updated conda-build-all to 1.0.2
