### ISSUE TITLE
Adding obvious-ci to defaults

### ISSUE THREAD

**Issue by jakirkham** [ContinuumIO/anaconda-recipes#95]
Not sure if this is the right place to ask this or not. Please feel free to redirect me to a more appropriate forum if not.

Given that `conda-build-all` is in `defaults`, was curious to see if `obvious-ci` could also be added to `defaults` as well. As the package does seem to be used by a larger community than just conda-forge, it seems reasonable for it to be in the `defaults` collection. Also nothing has changed substantially since the last release, which was ~1yr ago, as it is pretty stable. So the maintenance burden should be pretty light.

**Comment by msarahan** [comment]
I'd like to understand what would be gained by having it in defaults rather than conda-forge.  What examples can you provide of people who are using this package, who would like to avoid using conda-forge?  How is defaults more compatible with their wishes?

**Comment by mingwandroid** [comment]
I added `conda-build-all` to defaults upon customer request. I've never used it so don't know much about it.

How likely is a user of `conda-build-all` to also want to use `obvious-ci`, in your estimation?

**Comment by msarahan** [comment]
Closing, as obvious ci has been deprecated.
